language: php

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

env:
  - SYMFONY_VERSION='2.8.*'
  - SYMFONY_VERSION='3.0.*'

before_script:
  - php -i | grep "ICU version"
  - composer self-update
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
  - composer install --dev --prefer-source

script: phpunit --coverage-text

notifications:
  email:
    - willemsen.christophe@gmail.com
    - mb@lunetics.com

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
